### ISSUE TITLE
Quarterstaff filters out as available mage weapon

### ISSUE THREAD

**Issue by ATZ0** [syntax53/MMUD-Explorer#1]
Version 1.70

To replicate:

Apply a Global Filter for a Level 7 Mage, Alignment Good

Expected behavior:

quarterstaff (#100) will appear as an available weapon under "Weapons"

Actual behavior:

quarterstaff is filtered out. 
Will reappear if global filter removed.

**Comment by syntax53** [comment]
Verified that MajorMUD hardcodes items #s 68 (dagger) and # 100 (quarterstaff) as usable by "Limited" weapon classes.  So not really a bug.  Will add similar hard codes to MME next release.

**Comment by syntax53** [comment]
fixed for next release
