### ISSUE TITLE
Bug:  Placed items (chests, etc) do not pull up the room when double-clicking the reference

### ISSUE THREAD

**Issue by CuckooRules** [syntax53/MMUD-Explorer#11]
Simplest example to look at is the alder chest that spawns daily by Leo the Quick.  Item#974 (in my dats at least).  Spawns in Room: 9/863.  If you double-click that line, which would normally pull up the room, it switches to the Rooms tab but provides an error "Room 0/0 was not found".  I checked with other placed items and my suspicion is that it is an error surrounding references for which there is no % provided.  It also happens for the adamantite chest (the sign version) that is near Ozrinom.  The rooms exist and I have verified that they can be loaded manually in the same MME dat as well as that the items are indeed placed in the rooms indicated on the Sundry tab.

**Comment by syntax53** [comment]
Fixed on dev branch.

https://github.com/syntax53/MMUD-Explorer/commit/87f00f0c144e57fe4d2297d572572ec17b37c053
