### ISSUE TITLE
Minor Enhancement: Daily usage item verbiage for items where the Max uses and recharge vary

### ISSUE THREAD

**Issue by CuckooRules** [syntax53/MMUD-Explorer#12]
Currently, when viewing an item with daily uses MME displays the maximum uses as per day, when there is really no requirement that the Recharge on an item match the maximum uses.  Here is how an item with 100 maximum uses and 25 daily recharges shows currently:

Abilities: LoyalItem, Recharge +25 -- Uses: 100x/day

It would be preferable if the verbiage could somehow more accurately reflect that this regains 25 uses a day but could potentially hold up to 100 total uses at any given time.

**Comment by syntax53** [comment]
The following items (in mudrev dats) have "UseCount > 0" and "Retain After Uses = Yes" but do NOT have a recharge ability.  Do these items never get uses back?  Just trying to confirm.

Number	Name					UseCount		Retain After Uses
425		crimson bracers			3			1
1456	bloodstone ring			3			1
1657	shamanic headdress			10			1
1729	diamond willow staff			9999		1
2086	embroidered black tunic		10			1
2087	embroidered black leggings	10			1
2088	embroidered black boots		10			1
2277	Archer's Cloak				3			1
2693	Blessed Ivory Mask			3			1
2699	Starmetal Bracers			4			1
3170	embroidered red tunic		10			1
3171	embroidered red leggings		10			1
3172	embroidered red boots		10			1
3507	Divine Staff				1			1
3506	Staff of Wicca				1			1

**Comment by CuckooRules** [comment]
Probably an error or oversight in editing.  One i just removed the uses because it didnt cast anything (Blessed ivory mask)  You could hide the uses flag from the users in that case but also how i knew to go fix it.  i will examine this list in my dats.  Thank you.


Sent from my Sprint Samsung Galaxy S7.
-------- Original message --------From: Matt <notifications@github.com> Date: 2/12/17  10:05 PM  (GMT-06:00) To: syntax53/MMUD-Explorer <MMUD-Explorer@noreply.github.com> Cc: CuckooRules <i.am.cuckoo@gmail.com>, Author <author@noreply.github.com> Subject: Re: [syntax53/MMUD-Explorer] Minor Enhancement: Daily usage item
  verbiage for items where the Max uses and recharge vary (#12) 
The following items (in mudrev dats) have "UseCount > 0" and "Retain After Uses = Yes" but do NOT have a recharge ability.  Do these items never get uses back?  Just trying to confirm.
Number	Name					UseCount		Retain After Uses

425		crimson bracers			3			1

1456	bloodstone ring			3			1

1657	shamanic headdress			10			1

1729	diamond willow staff			9999		1

2086	embroidered black tunic		10			1

2087	embroidered black leggings	10			1

2088	embroidered black boots		10			1

2277	Archer's Cloak				3			1

2693	Blessed Ivory Mask			3			1

2699	Starmetal Bracers			4			1

3170	embroidered red tunic		10			1

3171	embroidered red leggings		10			1

3172	embroidered red boots		10			1

3507	Divine Staff				1			1

3506	Staff of Wicca				1			1

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/syntax53/MMUD-Explorer","title":"syntax53/MMUD-Explorer","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/syntax53/MMUD-Explorer"}},"updates":{"snippets":[{"icon":"PERSON","message":"@syntax53 in #12: The following items (in mudrev dats) have \"UseCount \u003e 0\" and \"Retain After Uses = Yes\" but do NOT have a recharge ability.  Do these items never get uses back?  Just trying to confirm.\r\n\r\nNumber\tName\t\t\t\t\tUseCount\t\tRetain After Uses\r\n425\t\tcrimson bracers\t\t\t3\t\t\t1\r\n1456\tbloodstone ring\t\t\t3\t\t\t1\r\n1657\tshamanic headdress\t\t\t10\t\t\t1\r\n1729\tdiamond willow staff\t\t\t9999\t\t1\r\n2086\tembroidered black tunic\t\t10\t\t\t1\r\n2087\tembroidered black leggings\t10\t\t\t1\r\n2088\tembroidered black boots\t\t10\t\t\t1\r\n2277\tArcher's Cloak\t\t\t\t3\t\t\t1\r\n2693\tBlessed Ivory Mask\t\t\t3\t\t\t1\r\n2699\tStarmetal Bracers\t\t\t4\t\t\t1\r\n3170\tembroidered red tunic\t\t10\t\t\t1\r\n3171\tembroidered red leggings\t\t10\t\t\t1\r\n3172\tembroidered red boots\t\t10\t\t\t1\r\n3507\tDivine Staff\t\t\t\t1\t\t\t1\r\n3506\tStaff of Wicca\t\t\t\t1\t\t\t1\r\n\r\n"}],"action":{"name":"View Issue","url":"https://github.com/syntax53/MMUD-Explorer/issues/12#issuecomment-279290097"}}}

**Comment by CuckooRules** [comment]
Finally had time to look.  None of these actually had any spell attached,
so these were just likely items copied and not cleaned up.  I just cleaned
them all up on my copy of the dats.  Thanks for the list.  I don't have
access or any common db browser to look at the dats for stuff like this
more easily.  I should probably work on that, but busy trying to decode the
DLL.  Lol.

**Comment by syntax53** [comment]
People underestimate MS Access.  That's all I used.

**Comment by CuckooRules** [comment]
My new PC doesnt even have Access.  It apparently didnt install with office
and I havent pursued it very far.

**Comment by syntax53** [comment]
fixed in https://github.com/syntax53/MMUD-Explorer/commit/aac9536388c1c488535f17d32fd87e9e52e2830d

changed "x/day" on uses to "start/max"
