### ISSUE TITLE
Filter for monsters not working correctly

### ISSUE THREAD

**Issue by CuckooRules** [syntax53/MMUD-Explorer#13]
If I apply a filter of Magic <= 2 and leave all the other filters as default and click apply, Champion of Blood (magic 0) disappears from the list as does massive black harpy and others.  I don't think this is working correctly, but strangely it did leave many magic 0 monsters both of the placed NPC/boss variety as well as regular monsters.  Not really sure what's going on here, but in my eyes this isn't usable because the results aren't reliable.

**Comment by syntax53** [comment]
Side note-- "Remove Filter" also not remove the magic filter

**Comment by syntax53** [comment]
Fixed in dev.  Magic level was not being reset while looping through monsters to filter.
