### ISSUE TITLE
Incorrect Accuracy on Weapons tab when using accuracy field + accuracy ability

### ISSUE THREAD

**Issue by CuckooRules** [syntax53/MMUD-Explorer#15]
There is a bug with the display for Accuracy values on weapons on the Weapons tab.  In NMR, there is an Accuracy field directly attached to items in addition to the Accuracy ability.  If a weapon contains BOTH, it seems that the value from the ability is "winning" and displaying, instead of displaying the sum of both values.  If only one or the other value exists, it seems to display correctly.  Additionally, the Equipment tab seems to show the correct value for these items which is what initially lead me to discover this.  It appears to be working correctly for Items as well as on the Equipment tab, so I believe it is specific to the Weapons tab Accuracy column.  The item I initially found this on was for bloodstained sickle on MudRev, however you can filter on the Accuracy ability being >1 and likely find some other examples if you do not have the same values in your dats.

**Comment by syntax53** [comment]
Are you sure that both values apply to weapons?  There is a chance that I knew only the one would be applied when originally coding it.  Couldn't remember for the life of me now though.

**Comment by syntax53** [comment]
fixed: https://github.com/syntax53/MMUD-Explorer/commit/403681cf34fef9af27e6a3b2492028b65ed4635a
