### ISSUE TITLE
"Room 0/0 not found" error when double clicking reference on Placed Items (Sundry tab)

### ISSUE THREAD

**Issue by CuckooRules** [syntax53/MMUD-Explorer#16]
Example:

Sundry tab
1299 withered tree

Reference shows the room where this exists:

Room:  Hedge Maze (17/2897)
Double click to pull up the room on map

Receive error:

"Room 0/0 not found"

**Comment by syntax53** [comment]
also an issue on items

**Comment by syntax53** [comment]
fixed: https://github.com/syntax53/MMUD-Explorer/commit/664eeb1f040ada8b47864d3ef8522f5581f6f08b
