### ISSUE TITLE
Enhancement:  Find Readyable Items on Sundry Tab

### ISSUE THREAD

**Issue by CuckooRules** [syntax53/MMUD-Explorer#18]
Presently, there isn't really any concise way of searching for Readyable items other than hoping they exist with a Type of Light.  Readyable items are any item with the TargetIllu ability on it.  The Ability filter doesn't exist on the Sundry tab or else they could just be searched that way.

**Comment by syntax53** [comment]
resolved by adding an ability filter to the sundry tab: https://github.com/syntax53/MMUD-Explorer/commit/8a8d3045c6435fb37973222f9bb3af5993604039
