### ISSUE TITLE
Remote Action in textblocks with no map specified displays incorrect room

### ISSUE THREAD

**Issue by CuckooRules** [syntax53/MMUD-Explorer#19]
When reading textblocks in MME, if it uses a remoteaction with a 0 for the map (meaning current map?), MME defaults to the map that is being used on the map tab, resulting in the remote action showing for a room that makes no sense.  Example is the stone sphinxes for the Pyramid.  If your map tab is set to map 1 and you open any of the stone sphinx greet textblocks, it shows that the remoteaction is on the labyrinth.  Changing the map to map 2 and re-visiting changes it to show as the corresponding room for map 2, etc.   This is a fairly minor issue, but if there is a way to provide context around where a textblock is called from, this is maybe possible to correct.  It caused me some confusion when I thought the pyramid textblocks were pointing to the labyrinth.

**Comment by syntax53** [comment]
workaround attempted by looping through the monster detail window first looking for regen rooms ("Room: xyz 1/23") and then falling back on group/lair rooms, before then defaulting to the map currently on the room tab: https://github.com/syntax53/MMUD-Explorer/commit/aa14db329898d681c6df0b8a4c4f88a3fca714ae
