### ISSUE TITLE
Request: Tweak equipment / "Find Best" to use AC/ENC values

### ISSUE THREAD

**Issue by ATZ0** [syntax53/MMUD-Explorer#2]
It'd be useful if equipment / "Find best" items displayed the item with the lowest encumbrance first when all other things (AC/DR) are equal across a list of multiple, matching items. (Make use of the calculated AC/ENC values shown on item lists) 

As an example, the "find best" will select black, red, orange, green, white (and other colors) of robes when clicking "Next best" before reaching silk robes, which offer the same AC/DR values but at a AC/ENC multiple of two higher.

**Comment by syntax53** [comment]
completed for next release
