### ISSUE TITLE
Enhancement: Mana Efficiency for Attack Spells

### ISSUE THREAD

**Issue by ATZ0** [syntax53/MMUD-Explorer#4]
Request to add a "Mana Efficiency / Damage" or other similarly labeled column to spells. This would functionally be the equivalent of the Dmg / Spd calculation for spellcasters, and give a read of the mana efficiency of attack spells by using the global filter scaling data in addition to a new calculation of:
((min dmg+maxdmg)/2)/mana cost

**Comment by syntax53** [comment]
done
